# Setup
title:        Are we consuming more local?
tagline:      Is Switzerland consuming more local products, or still imports the majoriy of food the country consumes?
baseurl:      "https://github.com/MrymZakani/ADA-project"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Valentine Bernasconi
  url:        http://www.valentinebernasconi.ch 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown